package br.com.zup.loginfirebase.utils

const val USER_KEY = "user"
const val NAME_ERROR_MESSAGE = "Favor informar nome"
const val EMAIL_ERROR_MESSAGE = "Favor informar email"
const val PASSWORD_ERROR_MESSAGE = "Favor informar senha"
const val CREATE_USER_ERROR_MESSAGE = "Erro ao criar usuário!"
const val LOGIN_ERROR_MESSAGE = "Não foi possivel realizar o login!"
const val IMAGE_COFFEE_ERROR_MESSAGE = "Tivemos um problema ao carregar a imagem!"
const val IMAGE_COFFEE_PATH = "cafeteriasimcity"
const val FAVORITE_PATH = "favoritos"
const val FAVORITE_MESSAGE = "Imagem favoritada com sucesso!"
const val APP_PATH = "myfirebase"
const val TEXT_PATH = "text"
const val Text_SAVED_MSG = "Sua frase foi salva com sucesso"